# Project Instructions for AI Agents

## Project Overview
Terraform Provider for Grafana/Grafana Cloud. Implements resources and data
sources for infrastructure-as-code via the Terraform Plugin SDK and Framework.
Docs are generated from schema, examples, and templates; manual edits to
docs/ are forbidden (see Constitution).

> **Note**: This file is generated by `/speckit.instructions`. Custom content is preserved during updates.

## Documentation Map
This project documentation is distributed across several key files. You MUST refer to these documents for specific details:

| Document | Location | Purpose | Key Content |
|----------|----------|---------|-------------|
| **Constitution** | `.specify/memory/constitution.md` | Single source of truth for principles | Coding standards, architectural rules, constraints |
| **Feature Index** | `.specify/memory/features.md` | Feature roadmap status | List of project features |
| **Readme** | `README.md` | Setup and usage | Local dev, tests, doc generation, release steps |
| **Docs (generated)** | `docs/` | Provider documentation | Generated via tfplugindocs from schema/examples/templates |
| **Codegen/Docs Templates** | `templates/` | Doc template inputs | tfplugindocs templates |
| **Build/Test Targets** | `GNUmakefile` | Commands | build, testacc*, docs, lint, release |

> **Directive**: When answering questions or generating code, ALWAYS check the relevant document from the map above first.

## Tech Stack & Resources
- **Project Name**: terraform-provider-grafana
- **Root Path**: /cws_data/terraform-provider-grafana

- **Languages**: Go 1.25.3
- **Frameworks/SDKs**: Terraform Plugin SDK v2, Terraform Plugin Framework
- **Tooling**: tfplugindocs, GoReleaser, golangci-lint
- **Key Directories**:
  - `internal/`: Provider implementation
  - `pkg/`: generation and shared utilities
  - `docs/`: generated docs (no manual edits)
  - `templates/`, `examples/`: doc inputs
  - `scripts/`, `tools/`: repo automation
  - `cmd/`: generators and auxiliary binaries

## Workflow Highlights
- **Build**: `go build` or `make build`.
- **Docs**: `go generate ./...` (updates `docs/` via tfplugindocs).
- **Acceptance tests**: `make testacc`, `make testacc-oss-docker`,
  `make testacc-enterprise-docker`, `make testacc-cloud-*`.
- **Lint**: `make golangci-lint` (dockerized).
- **Release**: `make release` tags and triggers GoReleaser.

## Conventions & Constraints
- Do not edit generated docs under `docs/`; update schema descriptions,
  `examples/`, or `templates/` instead.
- Follow Constitution Feature-centric development: update Feature Index when
  adding, splitting, or removing features.

# Tool And Skills Usage Guide

> **Note**: Tool and Skills details are injected into prompts by the agent when needed. This section is guidance only.

## Suggested Tooling Scope (High-Level)
- System/Linux CLI and shell context (env vars, functions, aliases)
- Project scripts (Shell/Python) when available
- MCP tools and skills (auto-injected; avoid duplicating details here)

## Guidance
- Prefer project scripts for repeatable tasks.
- Use MCP tools for internal docs or code queries when available.
- Verify architectural rules via the **Constitution** rather than assumptions.

## Tools
Project specific tools documentation can be found in `.ai/tools/`.
- [MCP Tools](.ai/tools/mcp.md)
- [System Tools](.ai/tools/system.md)
- [Shell Tools](.ai/tools/shell.md)
- [Project Scripts](.ai/tools/project.md)

## Skills
Project specific skills documentation can be found in `.github/skills/`.
